#!/bin/bash
# source function library
. /etc/rc.d/init.d/functions
# chkconfig: 345 85 15
# description: This is a haoCoding Test Service.
usage() {
	echo " usage:$0 {start|stop|restart} "
}

start() {
	echo "haoCoding Service Started!"
}

stop() {
	echo "haoCoding Service Stopped!"
}

restart() {
	stop
	start
}

#main function
case $1 in
  start)
     start
     ;;
  stop)
     stop
     ;;
  restart)
     restart
     ;;
  *)
     usage
     ;;
esac
